#!/bin/sh

if [[ `amixer -D pulse sget Capture` == *"[on]"* ]]; then
	MSG="%{F#807BF7} %{F-}"`amixer -D pulse sget Capture | grep -oE '\[[^]]+\]' | sed 's/\[//;s/\]//' | head -n1` 
else
	MSG="%{F#807BF7} %{F#707880}muted"
fi
echo $MSG
