#!/bin/bash

mkdir -p /tmp/monitorswitch
rm -r /tmp/monitorswitch/* > /dev/null 2>&1

output=$(xrandr --listmonitors)

MONITOR_COUNT=$(awk '/Monitors:/ {print $2}' <<< "$output")

while IFS= read -r line; do
  line=($line)
  id=${line[0]%%:*}
  name=${line[-1]}

  echo "$name" > "/tmp/monitorswitch/$id"
done < <(tail -n +2 <<< "$output")
