#!/bin/sh

for temp in `cat /sys/class/thermal/thermal_zone*/temp`
do
	TEMPERATURE=`expr $TEMPERATURE + $temp`
	COUNT=`expr $COUNT + 1`
done

TEMPERATURE=`expr $TEMPERATURE / 1000 / $COUNT`

if [ $TEMPERATURE -gt 60 ]
then
	ICON=
elif [ $TEMPERATURE -gt 40 ]
then
	ICON=懲
else
	ICON=
fi
echo %{F#A780E9}$ICON %{F-}$TEMPERATURE°C
