[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x5c6370"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xe6efff"
yellow = "0xd19a66"

[colors.dim]
black = "0x1e2127"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0x828791"
yellow = "0xd19a66"

[colors.normal]
black = "0x1e2127"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0x828791"
yellow = "0xd19a66"

[colors.primary]
background = "0x000000"
bright_foreground = "0xe6efff"
foreground = "0xd1c2e9"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.00"

[font]
size = 12.0

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "BoldItalic"

[font.italic]
family = "JetBrains Mono"
style = "MediumItalic"

[font.normal]
family = "JetBrains Mono"
style = "Medium"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "ReceiveChar"
mouse = "Right"
